[workspace]

members = [
    "banchmarks/*",
    "flex-btree",
    
    
    #"flex-tools",
    # "utils",
    # "flex-trie",
    # "flex-tools",
    # "flex-btree",
    # "flex-value",
    # "flex-linear-hash",
]