[workspace]

members = [
    "page-lock",
    "flex-page",

    # "utils",
    # "flex-trie",
    # "flex-bplus-tree",
    # "flex-tools",
    # "flex-btree",
    # "flex-value",
    # "flex-linear-hash",
]