[workspace]

members = [
    "byte-seeker",

    # "flex-trie",

    # "flex-bplus-tree",
    # "flex-page2",

    # "flex-tools",
    # "flex-page",
    # "flex-btree",
    # "flex-value",
    # "flex-linear-hash",
]