
fn_args_layout = "Compressed"
overflow_delimited_expr = true
use_field_init_shorthand = true
struct_field_align_threshold = 5

# !Stable

fn_single_line = true
imports_granularity = "Module"
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
enum_discrim_align_threshold = 10

# heuristics

use_small_heuristics = "Max"
