
fn_args_layout = "Compressed"
overflow_delimited_expr = true
use_field_init_shorthand = true
struct_field_align_threshold = 5

# !Stable

reorder_impl_items = true
imports_granularity = "Module"
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
enum_discrim_align_threshold = 10

# fn_single_line = true
# format_strings = true
# format_macro_matchers = true

# heuristics

# use_small_heuristics = "Off"
max_width = 125

chain_width = 80
array_width = 60
fn_call_width = 60
struct_lit_width = 60
struct_variant_width = 60
attr_fn_like_width = 70
single_line_if_else_max_width = 50