merge_imports = true
fn_single_line = true
fn_args_layout = "Compressed"
reorder_impl_items = true
overflow_delimited_expr = true
format_code_in_doc_comments = true
use_small_heuristics = "Max"
use_field_init_shorthand = true
struct_field_align_threshold = 20