[package]
name = "flex-page"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "*", default-features = false, features = ["rt"] }
data-view = "2"
page-lock = "1"

[dev-dependencies]