[package]
name = "flex-page"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-seeker = { path = "../byte-seeker" }
tokio = { version = "*", default-features = false, features = ["rt"] }
dashmap = "5.0.0"

[dev-dependencies]
tokio = { version = "1.14.0", features = ["macros", "time"] }