[package]
name = "flex-btree"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = "1"
flex-page = "1"
async-recursion = "1"

[dev-dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "macros"] }