[package]
name = "page-lock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
tokio = { version = "1.14.0", features = ["rt", "macros", "time"] }