[package]
name = "page-lock"
version = "0.1.0"
edition = "2021"
description = "An async library for locking page addresses"
authors = ["Nur <nurmohammed840@gmail.com>"]
repository = "https://github.com/nurmohammed840/flex"
keywords = ["lock", "async"]

[dependencies]