[package]
name = "flex-bplus-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-seeker = { path = "../byte-seeker" }
