[package]
name = "page"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = "1"
flex-page = "0.2"

[dev-dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "macros"] }